import {notFound} from "next/navigation";
import {boundedNeighborhood} from "@/domain/graph/algorithms";
import {edges as fixtureEdges,energyGraph,ideas as fixtureIdeas,peter} from "@/domain/graph/fixtures";
import type {PublicGraph,PublicIdea,PublicProfile,RelationType} from "@/domain/graph/model";
import {hasSupabase} from "@/lib/env";
import {createPublicSupabaseClient} from "@/lib/supabase/public";

type NodeRow={id:string;slug:string;graph_id:string;author_id:string;title:string;summary:string;node_type:PublicIdea["type"];maturity:string;published_at:string|null;current_version_id:string|null};
type EdgeRow={id:string;source_node_id:string;target_node_id:string;relation_type:RelationType};
const nodeSelect="id,slug,graph_id,author_id,title,summary,node_type,maturity,published_at,current_version_id";
const looksLikeUuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
const fallbackProfile:PublicProfile={id:"unknown",username:"creator",displayName:"Creator",bio:""};
const toProfile=(row:{id:string;username:string;display_name:string;bio:string}):PublicProfile=>({id:row.id,username:row.username,displayName:row.display_name,bio:row.bio});
function toIdea(row:NodeRow,creator:PublicProfile,description?:string):PublicIdea{return{id:row.id,slug:row.slug,graphId:row.graph_id,title:row.title,summary:row.summary,description:description||row.summary,type:row.node_type,maturity:row.maturity,creator,publishedAt:row.published_at||new Date(0).toISOString(),branchCount:0}}
async function profileMap(ids:string[]){const client=createPublicSupabaseClient();if(!client)return new Map<string,PublicProfile>();const{data}=await client.from("profiles").select("id,username,display_name,bio").in("id",[...new Set(ids)]);return new Map((data||[]).map(row=>[row.id,toProfile(row)]))}
async function mapNodes(rows:NodeRow[]){const profiles=await profileMap(rows.map(row=>row.author_id));return rows.map(row=>toIdea(row,profiles.get(row.author_id)||fallbackProfile))}

export async function getFeaturedIdeas(){if(!hasSupabase)return fixtureIdeas.slice(0,9);const client=createPublicSupabaseClient();const{data}=await client!.from("nodes").select(nodeSelect).eq("status","published").eq("visibility","public").is("deleted_at",null).order("published_at",{ascending:false}).limit(9);return mapNodes((data||[]) as NodeRow[])}
export async function getProfile(username:string){if(!hasSupabase){if(username.toLowerCase()!==peter.username)notFound();return peter}const client=createPublicSupabaseClient();const{data}=await client!.from("profiles").select("id,username,display_name,bio").ilike("username",username).single();if(!data)notFound();return toProfile(data)}
export async function getCreatorGraphs(username:string){if(!hasSupabase){await getProfile(username);return[energyGraph]}const owner=await getProfile(username);const client=createPublicSupabaseClient();const{data}=await client!.from("graphs").select("id,slug,title,description,root_node_id").eq("owner_id",owner.id).eq("visibility","public").is("deleted_at",null);return(data||[]).map(row=>({id:row.id,slug:row.slug,title:row.title,description:row.description,owner,rootNodeId:row.root_node_id||""}))}
export async function getGraph(slug:string):Promise<PublicGraph>{if(!hasSupabase){if(slug!==energyGraph.slug&&slug!==energyGraph.id)notFound();return energyGraph}const client=createPublicSupabaseClient();let query=client!.from("graphs").select("id,slug,title,description,owner_id,root_node_id").eq("slug",slug);if(looksLikeUuid(slug))query=client!.from("graphs").select("id,slug,title,description,owner_id,root_node_id").eq("id",slug);const{data,error}=await query.single();if(error){console.error(JSON.stringify({event:"public_data.error",resource:"graph",code:error.code,message:error.message}));throw new Error("Public graph data unavailable")}if(!data)notFound();const profiles=await profileMap([data.owner_id]);return{id:data.id,slug:data.slug,title:data.title,description:data.description,owner:profiles.get(data.owner_id)||fallbackProfile,rootNodeId:data.root_node_id||""}}
export async function getIdea(slug:string){if(!hasSupabase){const idea=fixtureIdeas.find(item=>item.slug===slug||item.id===slug);if(!idea)notFound();return idea}const client=createPublicSupabaseClient();let query=client!.from("nodes").select(nodeSelect).eq("slug",slug);if(looksLikeUuid(slug))query=client!.from("nodes").select(nodeSelect).eq("id",slug);const{data,error}=await query.single();if(error){console.error(JSON.stringify({event:"public_data.error",resource:"idea",code:error.code,message:error.message}));throw new Error("Public idea data unavailable")}if(!data)notFound();const row=data as NodeRow;const[profiles,version,mediaLinks,sourceLinks,branchCount]=await Promise.all([profileMap([row.author_id]),row.current_version_id?client!.from("node_versions").select("content_json").eq("id",row.current_version_id).single():Promise.resolve({data:null}),client!.from("node_artifacts").select("role,artifacts(title,external_url,metadata_json)").eq("node_id",row.id),client!.from("node_sources").select("sources(title,url,publisher)").eq("node_id",row.id),client!.from("lineage_links").select("id",{count:"exact",head:true}).eq("source_node_id",row.id)]);const content=version.data?.content_json as {body?:string}|null;const idea=toIdea(row,profiles.get(row.author_id)||fallbackProfile,content?.body);idea.branchCount=branchCount.count||0;const mediaRecord=(mediaLinks.data?.[0] as unknown as {artifacts:{title:string;external_url:string;metadata_json:{provider?:"soundcloud"|"spotify"|"apple_music"}}}|undefined)?.artifacts;if(mediaRecord?.external_url)idea.media={provider:mediaRecord.metadata_json?.provider||"soundcloud",url:mediaRecord.external_url,title:mediaRecord.title};idea.sources=(sourceLinks.data||[]).map(item=>(item as unknown as {sources:{title:string;url:string;publisher:string}}).sources).filter(Boolean);return idea}
export async function getGraphIdeas(graphId:string){if(!hasSupabase){if(graphId!==energyGraph.id)notFound();return fixtureIdeas}const client=createPublicSupabaseClient();const{data}=await client!.from("nodes").select(nodeSelect).eq("graph_id",graphId).eq("status","published").is("deleted_at",null).order("published_at");return mapNodes((data||[]) as NodeRow[])}
export async function getConnections(nodeId:string){if(!hasSupabase){return fixtureEdges.filter(edge=>edge.sourceNodeId===nodeId||edge.targetNodeId===nodeId).map(edge=>({edge,idea:fixtureIdeas.find(item=>item.id===(edge.sourceNodeId===nodeId?edge.targetNodeId:edge.sourceNodeId))!}))}const client=createPublicSupabaseClient();const{data}=await client!.from("edges").select("id,source_node_id,target_node_id,relation_type").or(`source_node_id.eq.${nodeId},target_node_id.eq.${nodeId}`).is("deleted_at",null).limit(50);const rows=(data||[]) as EdgeRow[];const ids=rows.map(row=>row.source_node_id===nodeId?row.target_node_id:row.source_node_id);const{data:nodes}=ids.length?await client!.from("nodes").select(nodeSelect).in("id",ids):{data:[]};const mapped=await mapNodes((nodes||[]) as NodeRow[]);return rows.map(row=>({edge:{id:row.id,sourceNodeId:row.source_node_id,targetNodeId:row.target_node_id,relationType:row.relation_type},idea:mapped.find(item=>item.id===(row.source_node_id===nodeId?row.target_node_id:row.source_node_id))!})).filter(item=>item.idea)}
export async function getNeighborhood(graphId:string,focusId:string,limit=7){if(!hasSupabase){if(graphId!==energyGraph.id)notFound();const focus=fixtureIdeas.find(item=>item.id===focusId);if(!focus)notFound();return{focus,...boundedNeighborhood(fixtureIdeas,fixtureEdges,focusId,limit)}}const focus=await getIdea(focusId);if(focus.graphId!==graphId)notFound();const connections=await getConnections(focusId);const nodes=[focus,...connections.map(item=>item.idea)];const neighborhood=boundedNeighborhood(nodes,connections.map(item=>item.edge),focusId,limit);return{focus,...neighborhood}}
export async function searchIdeas(query:string):Promise<PublicIdea[]>{const q=query.trim();if(!q)return[];if(!hasSupabase){const normalized=q.toLocaleLowerCase();return fixtureIdeas.filter(idea=>`${idea.title} ${idea.summary}`.toLocaleLowerCase().includes(normalized)).slice(0,20)}const client=createPublicSupabaseClient();const{data}=await client!.rpc("search_public_ideas",{p_query:q,p_limit:20});const ids:string[]=((data||[]) as Array<{id:string}>).map(row=>row.id);if(!ids.length)return[];const{data:nodes}=await client!.from("nodes").select(nodeSelect).in("id",ids);const mapped=await mapNodes((nodes||[]) as NodeRow[]);return ids.map(id=>mapped.find((item:PublicIdea)=>item.id===id)).filter((item):item is PublicIdea=>Boolean(item))}
