import {notFound} from "next/navigation";
const content:Record<string,{title:string;intro:string;sections:Array<[string,string]>}>={
  about:{title:"About",intro:"Made by Peter is a branchable public record of ideas and execution.",sections:[["The promise","Share what you are learning and making. Let others grow it without losing where it came from."],["MVP status","This is an early product foundation. The marketplace and production AI integrations are not live."]]},
  terms:{title:"Terms",intro:"Plain-language placeholder terms for local MVP evaluation—not production legal terms.",sections:[["Your content","You retain responsibility for content and rights you publish."],["Lineage","Attribution records do not automatically create licences, royalties, partnerships, or equity."]]},
  privacy:{title:"Privacy",intro:"Private by default where it matters.",sections:[["Email","Authentication email stays private unless you separately choose a public contact address."],["AI","Private content is not used for training. Deterministic local adapters receive only the scope you submit."],["Choices","You can withdraw marketing consent, export account data, and request deletion."]]},
  rights:{title:"Rights and lineage",intro:"Ideas have histories; legal rights require more than a graph connection.",sections:[["Attribution","Reference, fork, and remix records preserve source, version, creator, date, and licence snapshot."],["Removal","Public-source removal and lineage tombstones require a documented legal/privacy policy before launch."]]},
  "community-guidelines":{title:"Community guidelines",intro:"Be useful, honest, and respectful of people and their work.",sections:[["Do","Credit sources, distinguish evidence from opinion, and report risks clearly."],["Do not","Post private data, impersonate creators, spam the graph, or misrepresent drafts and mocks as verified work."]]},
  today:{title:"Today",intro:"Recent public drops will appear here without paid ranking.",sections:[["MVP fixture","The seeded LNG lifecycle is the current featured public story."]]},
};
export default async function LegalPage({params}:{params:Promise<{legal:string}>}){const{legal}=await params;const page=content[legal];if(!page)notFound();return <main id="main" className="narrow prose"><p className="eyebrow">Made by Peter</p><h1>{page.title}</h1><p className="lede">{page.intro}</p>{page.sections.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}</main>}
